### ISSUE TITLE
Include documentation on getting started to test out this project

### ISSUE THREAD

**Issue by secretGeek** [pladams9/hexsheets#30]
I'm interested to see where this goes, and would love it if the readme had a little bit of getting started guidance.

(I may not have time to tinker just yet, but i would intend to send some python users toward this project if there was a little guidance as mentioned above)

good luck, and i understand if you're not ready to encourage others in just yet!

kind regards
lb

**Comment by secretGeek** [comment]
oooo.... fun.... I just managed to get started!

1. I cloned it locally
2. went to the `src` folder
3. ran `py .\hex-spreadsheet.py` at the commandline

...a beautiful honeycomb spreadsheet appeared. I successfully edited some cells. Saved a file. Edited more cells. Loaded the earlier file... No crashing!  

I wonder if formulae work yet.. a minimal example of a formula would be next "getting started" thing I want to know. ;)

**Comment by pladams9** [comment]
Hey! Thanks for trying it out. Yes, some basic formulae work, including referencing other cells. I've added some user documentation in the most recent version (if you download the [release version](https://github.com/pladams9/hexsheets/releases/tag/0.2.0) the help docs are included).

I will definitely get some more information into the readme about getting the project running from source as well.

**Comment by pladams9** [comment]
I've updated the [readme ](https://github.com/pladams9/hexsheets/blob/develop/README.md) on the `develop` branch. Let me know if that helps.

**Comment by secretGeek** [comment]
Perfect! Worked for me!
