### ISSUE TITLE
Square tiles in background of documentation

### ISSUE THREAD

**Issue by secretGeek** [pladams9/hexsheets#39]
I noticed the documentation had square tiles in the background. The enemy! The evil squares!!

![documentation](https://user-images.githubusercontent.com/2861690/83844471-690b7b00-a74a-11ea-97fc-393a6a2aacc1.png)

So I've built a hexagonal grid.png file as a drop replacement for the square grid.png file... but don't know how to replace it in the repo (I don't know much about python, mkdocs, etc.)

please see: 

![image](https://user-images.githubusercontent.com/2861690/83844586-9d7f3700-a74a-11ea-9ea7-c0f1fa108205.png)

**Comment by padams-nh** [comment]
That's awesome! I was planning on creating a new mkdocs theme as well (#35), so I'd love to incorporate this as well.

**Comment by pladams9** [comment]
That looks great! Would love to incorporate this into a new theme for mkdocs (#35). Currently just the default is applied.

**Comment by secretGeek** [comment]
should be resolved by #40
